pipeline {
    agent any
    stages {
        stage('Clean Up'){
            steps{
                sh "echo Cleaning up"
            }
        }
        
       
        stage('Run Python Script') {
            steps {
                sh 'python dockerfileexercise/Task1/app.py'
            }
        }
    }
}
